USE yungalaxy_z_251;

INSERT INTO logistics_base_role
(
  TenantID
 ,RoleID
 ,roleName
 ,Created
 ,Modified
 ,CreatedBy
 ,ModifiedBy
)
VALUES
(
  890501594632818690 -- TenantID - BIGINT(20) NOT NULL
 ,822501594632818690 -- RoleID - BIGINT(20) NOT NULL
 ,'member' -- roleName - VARCHAR(200) NOT NULL
 ,NOW() -- Created - TIMESTAMP(3) NOT NULL
 ,NOW() -- Modified - TIMESTAMP(3) NOT NULL
 ,890501594632818690 -- CreatedBy - BIGINT(20) NOT NULL
 ,890501594632818690 -- ModifiedBy - BIGINT(20) NOT NULL
);


INSERT INTO logistics_base_role
(
  TenantID
 ,RoleID
 ,roleName
 ,Created
 ,Modified
 ,CreatedBy
 ,ModifiedBy
)
VALUES
(
  890501594632818690 -- TenantID - BIGINT(20) NOT NULL
 ,822601594632818690 -- RoleID - BIGINT(20) NOT NULL
 ,'wareHouseAdmin' -- roleName - VARCHAR(200) NOT NULL
 ,NOW() -- Created - TIMESTAMP(3) NOT NULL
 ,NOW() -- Modified - TIMESTAMP(3) NOT NULL
 ,890501594632818690 -- CreatedBy - BIGINT(20) NOT NULL
 ,890501594632818690 -- ModifiedBy - BIGINT(20) NOT NULL
);



INSERT INTO logistics_base_role
(
  TenantID
 ,RoleID
 ,roleName
 ,Created
 ,Modified
 ,CreatedBy
 ,ModifiedBy
)
VALUES
(
  890501594632818690 -- TenantID - BIGINT(20) NOT NULL
 ,822701594632818690 -- RoleID - BIGINT(20) NOT NULL
 ,'customerService' -- roleName - VARCHAR(200) NOT NULL
 ,NOW() -- Created - TIMESTAMP(3) NOT NULL
 ,NOW() -- Modified - TIMESTAMP(3) NOT NULL
 ,890501594632818690 -- CreatedBy - BIGINT(20) NOT NULL
 ,890501594632818690 -- ModifiedBy - BIGINT(20) NOT NULL
);




INSERT INTO logistics_base_role
(
  TenantID
 ,RoleID
 ,roleName
 ,Created
 ,Modified
 ,CreatedBy
 ,ModifiedBy
)
VALUES
(
  890501594632818690 -- TenantID - BIGINT(20) NOT NULL
 ,822801594632818690 -- RoleID - BIGINT(20) NOT NULL
 ,'finance' -- roleName - VARCHAR(200) NOT NULL
 ,NOW() -- Created - TIMESTAMP(3) NOT NULL
 ,NOW() -- Modified - TIMESTAMP(3) NOT NULL
 ,890501594632818690 -- CreatedBy - BIGINT(20) NOT NULL
 ,890501594632818690 -- ModifiedBy - BIGINT(20) NOT NULL
);



INSERT INTO logistics_base_role
(
  TenantID
 ,RoleID
 ,roleName
 ,Created
 ,Modified
 ,CreatedBy
 ,ModifiedBy
)
VALUES
(
  890501594632818690 -- TenantID - BIGINT(20) NOT NULL
 ,822901594632818690 -- RoleID - BIGINT(20) NOT NULL
 ,'admin' -- roleName - VARCHAR(200) NOT NULL
 ,NOW() -- Created - TIMESTAMP(3) NOT NULL
 ,NOW() -- Modified - TIMESTAMP(3) NOT NULL
 ,890501594632818690 -- CreatedBy - BIGINT(20) NOT NULL
 ,890501594632818690 -- ModifiedBy - BIGINT(20) NOT NULL
);



--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.31.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2017/12/15 10:15:55
-- Server version: 5.6.16-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO yungalaxy_z_251.logistics_quotation_channel(TenantID, ID, Name, code, Prescription, Remark, Clause, Created, Modified, CreatedBy, ModifiedBy) VALUES
(890501594632818690, 890501594622318690, 'Fedx经济型', 'FedxEconomic', '', '', '', '2017-12-12 11:28:31', '2017-12-12 11:28:31', 890501594632818690, 890501594632818690);
INSERT INTO yungalaxy_z_251.logistics_quotation_channel(TenantID, ID, Name, code, Prescription, Remark, Clause, Created, Modified, CreatedBy, ModifiedBy) VALUES
(890501594632818690, 890501594622338690, 'UPS经济型', 'UPSEconomic', '3-至-10', '长宽高任意一边超60cm则计体积费用', '亚洲主要国家2-4工作日，澳洲、北美、欧洲5-7个工作日，其他国家8-10个工作日，ems（海运）7-12个工作日\r\n\r\n按实际重量计费（包裹尺寸长、宽、高任意一边超60cm需计算该包裹的体积重量，体积重量计算公式=(长×宽×高)cm÷6000），ems（普快）0.5kg为计费单位，ems（促销）0.05kg为计费单位，ems（海运）1kg为计费单位\r\n\r\nems（促销）暂时仅开通日韩、港台、新加坡、俄罗斯、英国、法国、荷兰、西班牙、乌克兰、加拿大、美国...等10多个国家，ems海运（仅开通韩国路向且只受理个人生活用品，可以邮寄液体与电池）\r\n\r\n一票一件一单号，单件重量上限为30kg，长≤1.5米，长+宽+高≤2.1米\r\n\r\n为了更顺利的进出口清关请去除包裹内关于商品价格的标签\r\n\r\n受理延误正式书面查询：10个工作日后，查询期：15个工作日，理赔期：7个工作日\r\n\r\n包裹遗失最高赔偿标准为国际运费的3倍，时效延误可申请退还服务费\r\n\r\n禁止运输：化工品、不明物品、电池、液体粉末、活体动植物、货币、管制刀具...\r\n\r\n国外退回的包裹免收退回运费', '2017-12-12 10:49:36', '2017-12-12 10:49:36', 890501594632818690, 890501594632818690);
INSERT INTO yungalaxy_z_251.logistics_quotation_channel(TenantID, ID, Name, code, Prescription, Remark, Clause, Created, Modified, CreatedBy, ModifiedBy) VALUES
(890501594632818690, 890501594622348690, 'DHL经济型', 'DHLEconomic', '3-至-10', '长宽高任意一边超60cm则计体积费用', '亚洲主要国家2-4工作日，澳洲、北美、欧洲5-7个工作日，其他国家8-10个工作日，ems（海运）7-12个工作日\r\n\r\n按实际重量计费（包裹尺寸长、宽、高任意一边超60cm需计算该包裹的体积重量，体积重量计算公式=(长×宽×高)cm÷6000），ems（普快）0.5kg为计费单位，ems（促销）0.05kg为计费单位，ems（海运）1kg为计费单位\r\n\r\nems（促销）暂时仅开通日韩、港台、新加坡、俄罗斯、英国、法国、荷兰、西班牙、乌克兰、加拿大、美国...等10多个国家，ems海运（仅开通韩国路向且只受理个人生活用品，可以邮寄液体与电池）\r\n\r\n一票一件一单号，单件重量上限为30kg，长≤1.5米，长+宽+高≤2.1米\r\n\r\n为了更顺利的进出口清关请去除包裹内关于商品价格的标签\r\n\r\n受理延误正式书面查询：10个工作日后，查询期：15个工作日，理赔期：7个工作日\r\n\r\n包裹遗失最高赔偿标准为国际运费的3倍，时效延误可申请退还服务费\r\n\r\n禁止运输：化工品、不明物品、电池、液体粉末、活体动植物、货币、管制刀具...\r\n\r\n国外退回的包裹免收退回运费', '2017-12-12 10:49:36', '2017-12-12 10:49:36', 890501594632818690, 890501594632818690);
INSERT INTO yungalaxy_z_251.logistics_quotation_channel(TenantID, ID, Name, code, Prescription, Remark, Clause, Created, Modified, CreatedBy, ModifiedBy) VALUES
(890501594632818690, 890501594622358690, 'TNT经济型', 'TNTEconomic', '3-至-10', '长宽高任意一边超60cm则计体积费用', '亚洲主要国家2-4工作日，澳洲、北美、欧洲5-7个工作日，其他国家8-10个工作日，ems（海运）7-12个工作日\r\n\r\n按实际重量计费（包裹尺寸长、宽、高任意一边超60cm需计算该包裹的体积重量，体积重量计算公式=(长×宽×高)cm÷6000），ems（普快）0.5kg为计费单位，ems（促销）0.05kg为计费单位，ems（海运）1kg为计费单位\r\n\r\nems（促销）暂时仅开通日韩、港台、新加坡、俄罗斯、英国、法国、荷兰、西班牙、乌克兰、加拿大、美国...等10多个国家，ems海运（仅开通韩国路向且只受理个人生活用品，可以邮寄液体与电池）\r\n\r\n一票一件一单号，单件重量上限为30kg，长≤1.5米，长+宽+高≤2.1米\r\n\r\n为了更顺利的进出口清关请去除包裹内关于商品价格的标签\r\n\r\n受理延误正式书面查询：10个工作日后，查询期：15个工作日，理赔期：7个工作日\r\n\r\n包裹遗失最高赔偿标准为国际运费的3倍，时效延误可申请退还服务费\r\n\r\n禁止运输：化工品、不明物品、电池、液体粉末、活体动植物、货币、管制刀具...\r\n\r\n国外退回的包裹免收退回运费', '2017-12-12 10:49:36', '2017-12-12 10:49:36', 890501594632818690, 890501594632818690);
INSERT INTO yungalaxy_z_251.logistics_quotation_channel(TenantID, ID, Name, code, Prescription, Remark, Clause, Created, Modified, CreatedBy, ModifiedBy) VALUES
(890501594632818690, 890501594632328690, 'EMS经济型', 'EMSEconomic', '3-至-10', '长宽高任意一边超60cm则计体积费用', '亚洲主要国家2-4工作日，澳洲、北美、欧洲5-7个工作日，其他国家8-10个工作日，ems（海运）7-12个工作日\r\n\r\n按实际重量计费（包裹尺寸长、宽、高任意一边超60cm需计算该包裹的体积重量，体积重量计算公式=(长×宽×高)cm÷6000），ems（普快）0.5kg为计费单位，ems（促销）0.05kg为计费单位，ems（海运）1kg为计费单位\r\n\r\nems（促销）暂时仅开通日韩、港台、新加坡、俄罗斯、英国、法国、荷兰、西班牙、乌克兰、加拿大、美国...等10多个国家，ems海运（仅开通韩国路向且只受理个人生活用品，可以邮寄液体与电池）\r\n\r\n一票一件一单号，单件重量上限为30kg，长≤1.5米，长+宽+高≤2.1米\r\n\r\n为了更顺利的进出口清关请去除包裹内关于商品价格的标签\r\n\r\n受理延误正式书面查询：10个工作日后，查询期：15个工作日，理赔期：7个工作日\r\n\r\n包裹遗失最高赔偿标准为国际运费的3倍，时效延误可申请退还服务费\r\n\r\n禁止运输：化工品、不明物品、电池、液体粉末、活体动植物、货币、管制刀具...\r\n\r\n国外退回的包裹免收退回运费', '2017-12-12 10:49:36', '2017-12-12 10:49:36', 890501594632818690, 890501594632818690);


